# Generated by Django 5.2.8 on 2025-11-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gravity', models.IntegerField(choices=[(1, 'Info'), (2, 'Warning'), (3, 'Critical')])),
                ('origin', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('log', models.ManyToManyField(to='base.log')),
            ],
            options={
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='base_anomal_timesta_d22f32_idx'), models.Index(fields=['gravity'], name='base_anomal_gravity_503b4d_idx'), models.Index(fields=['type'], name='base_anomal_type_6e0c46_idx'), models.Index(fields=['origin'], name='base_anomal_origin_b32bb6_idx')],
            },
        ),
    ]
