# Generated by Django 5.2.8 on 2025-11-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('RF_sensor', 'RF_sensor'), ('DF_sensor', 'DF_sensor'), ('camera', 'camera'), ('remote_id-sensor', 'remote_id-sensor'), ('radar', 'radar')])),
                ('position', models.TextField(max_length=256)),
                ('radar_range', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('RF_sensor', 'RF_sensor'), ('DF_sensor', 'DF_sensor'), ('camera', 'camera'), ('remote_id-sensor', 'remote_id-sensor'), ('radar', 'radar')])),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_position', models.CharField(max_length=256)),
                ('event_log', models.TextField()),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.radar')),
            ],
        ),
        migrations.DeleteModel(
            name='Anomaly',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
