# Generated by Django 5.2.8 on 2025-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_radar_detection_delete_anomaly_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField()),
                ('latitude', models.FloatField(max_length=256)),
                ('longitude', models.FloatField(max_length=256)),
                ('altitude', models.FloatField(max_length=256)),
                ('detected_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='radar',
            name='position',
        ),
        migrations.AddField(
            model_name='radar',
            name='altitude',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='radar',
            name='latitude',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='radar',
            name='longitude',
            field=models.FloatField(default=0, max_length=256),
        ),
    ]
