# Generated by Django 5.2.8 on 2025-11-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_radar_radar_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('paused', 'paused')]),
        ),
    ]
