# Generated by Django 5.2.8 on 2025-11-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_radar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='detected_radar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.radar'),
        ),
        migrations.CreateModel(
            name='EventDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_creation_date', models.DateTimeField(auto_now_add=True)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.radar')),
                ('related_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
