# Generated by Django 5.2.8 on 2025-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vehicle_remove_radar_position_radar_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='radar_range',
            field=models.FloatField(max_length=30),
        ),
    ]
